"use client";
import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import { MainSectionNav } from "@/app/components/MainSectionNav";
import { cloudFetch, type CloudClip, type CloudProject, type ProjectImage } from "@/lib/projects";
import { saveClipBoardHandoff } from "@/lib/clip-finder/handoff";
import { saveProjectImageHandoff } from "@/lib/project-image-handoff";
import styles from "./projects.module.css";

function time(seconds:number){const s=Math.max(0,seconds);return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`}
async function uploadImageFile(file:File):Promise<File>{
  if(file.size<=3.8*1024*1024)return file;
  if(file.type==="image/gif"||file.type==="image/heic"||file.type==="image/heif")throw new Error(`${file.name} is over 3.8 MB; choose a smaller copy`);
  const bitmap=await createImageBitmap(file);const scale=Math.min(1,2560/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));if(!blob||blob.size>3.8*1024*1024)throw new Error(`${file.name} could not be compressed below the upload limit`);return new File([blob],file.name.replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg"});
}
function ProjectsContent(){
  const router=useRouter(); const search=useSearchParams(); const selectedId=search.get("id"); const input=useRef<HTMLInputElement>(null);
  const [projects,setProjects]=useState<CloudProject[]>([]); const [project,setProject]=useState<CloudProject|null>(null); const [busy,setBusy]=useState(true); const [message,setMessage]=useState(""); const [uploading,setUploading]=useState(0); const [building,setBuilding]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const response=await cloudFetch(selectedId?`/api/projects/${selectedId}`:"/api/projects");const data=await response.json();if(selectedId)setProject(data);else setProjects(data);setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Could not load projects")}finally{setBusy(false)}},[selectedId]);
  useEffect(()=>{let current=true;void cloudFetch(selectedId?`/api/projects/${selectedId}`:"/api/projects").then(response=>response.json()).then(data=>{if(!current)return;if(selectedId)setProject(data);else setProjects(data);setMessage("")}).catch(e=>{if(current)setMessage(e instanceof Error?e.message:"Could not load projects")}).finally(()=>{if(current)setBusy(false)});return()=>{current=false}},[selectedId]);
  async function upload(files:FileList|null){if(!files||!selectedId)return;const all=Array.from(files);for(let i=0;i<all.length;i++){setUploading(Math.round(i/all.length*100));try{const image=await uploadImageFile(all[i]);const form=new FormData();form.append("image",image,image.name);await cloudFetch(`/api/projects/${selectedId}/images`,{method:"POST",body:form})}catch(e){setMessage(e instanceof Error?e.message:"Image upload failed");setUploading(0);return}}setUploading(100);await load();setTimeout(()=>setUploading(0),500)}
  async function build(clip:CloudClip){setBuilding(clip.id);setMessage("");try{const response=await cloudFetch(`/api/projects/media/clip/${clip.id}`);const audio=await response.blob();const id=crypto.randomUUID();await saveClipBoardHandoff({id,name:clip.title,audio,durationSec:clip.end_time-clip.start_time,transcript:clip.transcript,segments:[{start:0,end:clip.end_time-clip.start_time,text:clip.transcript}],createdAt:0});router.push(`/board2?clipImport=${encodeURIComponent(id)}`)}catch(e){setMessage(e instanceof Error?e.message:"Could not send clip to Board");setBuilding(null)} }
  async function openImagesInBoard(){if(!project?.project_images?.length)return;setMessage("Preparing project images for Board…");try{const images=await Promise.all(project.project_images.map(async(image,index)=>{const response=await cloudFetch(`/api/projects/media/image/${image.id}`);return{id:image.id,name:image.caption||`Project image ${index+1}`,blob:await response.blob()}}));const id=crypto.randomUUID();await saveProjectImageHandoff(id,images);router.push(`/board2?projectImages=${encodeURIComponent(id)}`)}catch(e){setMessage(e instanceof Error?e.message:"Could not open images in Board")}}
  return <main className={styles.page}><div className={styles.shell}><header className={`${styles.header} main-section-page-header`}><div><div className={styles.eyebrow}>Neuralboard</div><h1>{project?.name??"Projects"}</h1></div><MainSectionNav active="projects"/></header>
    {selectedId&&<button className={styles.back} onClick={()=>router.push("/projects")}>← All projects</button>}{message&&<p className={styles.error}>{message}</p>}{busy&&<p className={styles.muted}>Loading cloud projects…</p>}
    {!selectedId&&!busy&&(projects.length?<div className={styles.list}>{projects.map(p=><button className={styles.project} key={p.id} onClick={()=>router.push(`/projects?id=${p.id}`)}><h2>{p.name}</h2><div className={styles.muted}>{p.source_audio_name||"No source filename"}<br/>Updated {new Date(p.updated_at).toLocaleString()}</div></button>)}</div>:<div className={styles.empty}><b>No cloud projects yet.</b><p className={styles.muted}>Analyze a podcast in Clip Finder, then save its clips to a project.</p></div>)}
    {project&&!busy&&<><section className={styles.clips}>{(project.clips??[]).map(c=><article className={styles.clip} key={c.id}><div className={styles.clipHead}><div><h2>{c.title}</h2><div className={styles.meta}>{time(c.start_time)}–{time(c.end_time)} · {(c.end_time-c.start_time).toFixed(1)}s</div></div><button className={styles.button} disabled={building===c.id} onClick={()=>void build(c)}>{building===c.id?"Opening Board…":"Build video from this clip"}</button></div><p className={styles.reason}>{c.reason}</p><audio className={styles.audio} controls preload="metadata" src={`/api/projects/media/clip/${c.id}`} onError={()=>setMessage("Cloud storage unavailable — the Supabase project may be paused")}/><p className={styles.transcript}>{c.transcript}</p></article>)}{!(project.clips??[]).length&&<div className={styles.empty}>No clips saved in this project.</div>}</section>
      <section className={styles.imagesSection}><div className={styles.sectionHead}><div><h2>Project images</h2><div className={styles.muted}>Available on every signed-in device. Upload from your camera roll or Files.</div></div><div className={styles.upload}><input ref={input} hidden multiple type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/heic,image/heif" onChange={e=>{void upload(e.target.files);e.target.value=""}}/><button className={`${styles.button} ${styles.secondary}`} onClick={()=>input.current?.click()}>Upload images</button>{(project.project_images??[]).length>0&&<button className={styles.button} onClick={()=>void openImagesInBoard()}>Open images in Board</button>}</div></div>{uploading>0&&<><div className={styles.status}>Uploading… {uploading}%</div><div className={styles.progress}><div style={{width:`${uploading}%`}}/></div></>}<div className={styles.grid}>{(project.project_images??[]).map((image:ProjectImage)=><figure className={styles.imageCard} key={image.id}><Image fill unoptimized sizes="(max-width: 600px) 50vw, 180px" src={`/api/projects/media/image/${image.id}`} alt={image.caption||"Project image"}/>{image.caption&&<figcaption className={styles.caption}>{image.caption}</figcaption>}</figure>)}</div></section></>}
  </div></main>
}

export default function ProjectsPage(){return <Suspense fallback={<main className={styles.page}><div className={styles.shell}>Loading cloud projects…</div></main>}><ProjectsContent/></Suspense>}
