"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { publicBoardFetch, type PublicBoardPost } from "@/lib/public-board";
import styles from "./moderate.module.css";

export default function ModerationClient(){const [posts,setPosts]=useState<PublicBoardPost[]>([]);const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(async()=>{try{const response=await publicBoardFetch("/api/public-board/moderation");setPosts(await response.json());setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"Could not load submissions")}},[]);useEffect(()=>{let current=true;void publicBoardFetch("/api/public-board/moderation").then(response=>response.json()).then(data=>{if(current)setPosts(data)}).catch(e=>{if(current)setMessage(e instanceof Error?e.message:"Could not load submissions")});return()=>{current=false}},[]);
  async function act(action:"approve"|"reject"|"remove",ids:string[]){if(!ids.length)return;setBusy(true);try{await publicBoardFetch("/api/public-board/moderation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,ids})});setSelected([]);await load()}catch(e){setMessage(e instanceof Error?e.message:"Moderation failed")}finally{setBusy(false)}}
  const pending=posts.filter(post=>post.status==="pending"),approved=posts.filter(post=>post.status==="approved");return <main className={styles.page}><header><div><div className={styles.eyebrow}>Neuralboard owner</div><h1>Public Board moderation</h1></div><Link href="/public">View public board →</Link></header>{message?<p className={styles.message}>{message}</p>:null}<section><div className={styles.sectionHead}><h2>Pending ({pending.length})</h2><div><button disabled={busy||!selected.length} onClick={()=>void act("approve",selected)}>Approve selected</button><button className={styles.danger} disabled={busy||!selected.length} onClick={()=>void act("reject",selected)}>Delete selected</button></div></div>{pending.length?<div className={styles.grid}>{pending.map(post=><PostCard key={post.id} post={post} selected={selected.includes(post.id)} onSelect={checked=>setSelected(current=>checked?[...current,post.id]:current.filter(id=>id!==post.id))} actions={<><button disabled={busy} onClick={()=>void act("approve",[post.id])}>Approve</button><button className={styles.danger} disabled={busy} onClick={()=>void act("reject",[post.id])}>Delete</button></>}/>)}</div>:<div className={styles.empty}>No pending submissions.</div>}</section><section><h2>Live ({approved.length})</h2><div className={styles.grid}>{approved.map(post=><PostCard key={post.id} post={post} actions={<button className={styles.danger} disabled={busy} onClick={()=>void act("remove",[post.id])}>Remove from board</button>}/>)}</div></section></main>}

function PostCard({post,selected,onSelect,actions}:{post:PublicBoardPost;selected?:boolean;onSelect?:(checked:boolean)=>void;actions:React.ReactNode}){return <article className={styles.card}>{onSelect?<label className={styles.check}><input type="checkbox" checked={selected} onChange={e=>onSelect(e.target.checked)}/> Select</label>:null}{post.type==="image"?<div className={styles.image}><Image fill unoptimized sizes="320px" src={`/api/public-board/image/${post.id}`} alt="Submitted image"/></div>:null}{post.text?<p className={styles.text}>{post.text}</p>:null}<dl><div><dt>Name</dt><dd>{post.name||"Anonymous"}</dd></div><div><dt>Submitted</dt><dd>{new Date(post.created_at).toLocaleString()}</dd></div><div><dt>IP hash</dt><dd title={post.ip_hash}>{post.ip_hash?.slice(0,16)}…</dd></div></dl><div className={styles.actions}>{actions}</div></article>}
